{% set name = "msgpack-cxx" %}
{% set version = "6.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/msgpack/msgpack-c/archive/cpp-{{ version }}.tar.gz
    sha256: d7b119f292365d41403b41b40c2fefd82ebd81241e3c658fafe0e638fa54604a

build:
  number: 0
  run_exports:
    # 2023/05 -- hmaarrfk
    # Set to same pin as msgpack-c
    # https://github.com/conda-forge/msgpack-c-feedstock/blob/main/recipe/meta.yaml#L21
    - {{ pin_subpackage('msgpack-cxx', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - libboost-devel
    - zlib
  run:

test:
  commands:
    - test -f $PREFIX/include/msgpack.hpp  # [unix]
    - test -f $PREFIX/lib/cmake/msgpack-cxx/msgpack-cxx-config.cmake  # [unix]
    - if not exist %LIBRARY_INC%\\msgpack.hpp exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\msgpack-cxx\\msgpack-cxx-config.cmake exit 1  # [win]

about:
  home: https://github.com/msgpack/msgpack-c
  license: BSL-1.0
  license_file: COPYING
  summary: MessagePack implementation for C++

extra:
  feedstock-name: msgpack-cxx
  recipe-maintainers:
    - traversaro
    - hmaarrfk
